backend:
  name: git-gateway
  branch: "48891"  # o master, a seconda del tuo repo

media_folder: "assets/images"   # dove vengono salvate le immagini
public_folder: "/assets/images"  # percorso pubblico per le immagini

collections:
  # COLLEZIONE ARTICOLI
  - name: "articoli"
    label: "Articoli"
    folder: "_posts"  # directory dove vengono memorizzati gli articoli
    create: true  # permette di creare nuovi articoli direttamente dal CMS
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # formato slug per gli articoli
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }  # campo layout
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Categorie", name: "categories", widget: "list" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Keywords", name: "keywords", widget: "string" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Ref", name: "ref", widget: "string" }
      - { label: "Autore", name: "author", widget: "string" }
      - { label: "Lingua", name: "lang", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }

  # COLLEZIONE PAGINE
  - name: "pagine"
    label: "Pagine"
    folder: "_pages"  # directory per le pagine
    create: true  # permette di creare nuove pagine
    slug: "{{slug}}"  # formato slug per le pagine
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Keywords", name: "keywords", widget: "string" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Ref", name: "ref", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }  # campo layout
      - { label: "Autore", name: "author", widget: "string" }
      - { label: "Lingua", name: "lang", widget: "string" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
