  - name: "pagine_frame"
    label: "Pagine Frame"
    folder: "it"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "frame", name: "frame", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
